[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  pattern = "/(.*)(.pdf$)"
  to = "/"
  status = 403
  force = true

[[redirects]]
  from = "/npm/*"
  to = "https://cdn.jsdelivr.net/npm/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/gh/*"
  to = "https://cdn.jsdelivr.net/gh/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/wp/*"
  to = "https://cdn.jsdelivr.net/wp/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/avatar/*"
  to = "https://www.gravatar.com/avatar/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/unpkg/*"
  to = "https://unpkg.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/cdnjs/*"
  to = "https://cdnjs.cloudflare.com/ajax/libs/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/fonts/*"
  to = "https://fonts.googleapis.com/css:splat"
  status = 200
  force = true

[[redirects]]
  from = "/fonts-gstatic/*"
  to = "https://fonts.gstatic.com/s/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/jquery/*"
  to = "https://code.jquery.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/bootstrap/*"
  to = "https://stackpath.bootstrapcdn.com/bootstrap/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/fontawesome/*"
  to = "https://use.fontawesome.com/releases/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/gemini/*"
  to = "https://generativelanguage.googleapis.com/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "gzip, br"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"